# Generated by Django 4.2.7 on 2025-12-17 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feediscount',
            name='applicable_categories',
            field=models.CharField(blank=True, choices=[('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC'), ('GENERAL', 'General'), ('EWS', 'EWS'), ('MINORITY', 'Minority')], max_length=20, verbose_name='Applicable Categories'),
        ),
        migrations.AlterField(
            model_name='feediscount',
            name='required_documents',
            field=models.CharField(blank=True, choices=[('AADHAR', 'Aadhar Card'), ('INCOME', 'Income Certificate'), ('CASTE', 'Caste Certificate'), ('DOMICILE', 'Domicile Certificate'), ('BPL', 'BPL Card'), ('DISABILITY', 'Disability Certificate')], max_length=20, verbose_name='Required Documents'),
        ),
    ]
