# Generated by Django 4.2.7 on 2025-12-17 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0003_alter_feediscount_applicable_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='supporting_documents',
            field=models.CharField(blank=True, choices=[('BILL', 'Bill'), ('INVOICE', 'Invoice'), ('RECEIPT', 'Receipt'), ('VOUCHER', 'Payment Voucher'), ('QUOTATION', 'Quotation'), ('OTHER', 'Other')], max_length=30, null=True, verbose_name='Supporting Document'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_payments', to=settings.AUTH_USER_MODEL, verbose_name='Paid By'),
        ),
    ]
