# Generated by Django 4.2.7 on 2025-12-17 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_budget_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgettemplateitem',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.budgettemplate', verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='budgettemplate',
            name='template_items',
            field=models.ManyToManyField(help_text='Items to include in this template', related_name='template_items', to='finance.budgetitem', verbose_name='Template Items'),
        ),
    ]
