# Generated by Django 4.2.7 on 2025-12-18 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('communications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='recipient_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='Recipient ID'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='recipient_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Recipient Type'),
        ),
    ]
