# Generated by Django 4.2.7 on 2025-12-13 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0002_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmedicalinfo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='studentmedicalinfo',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='studentmedicalinfo',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_info', to='students.student', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='studentmedicalinfo',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant'),
        ),
        migrations.AddField(
            model_name='studentmedicalinfo',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='studentidentification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='studentidentification',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='studentidentification',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identification', to='students.student', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='studentidentification',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant'),
        ),
        migrations.AddField(
            model_name='studentidentification',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='students.studentdocument', verbose_name='Previous Version'),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant'),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL, verbose_name='Verified By'),
        ),
        migrations.AddField(
            model_name='studentaddress',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='studentaddress',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='studentaddress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='students.student', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='studentaddress',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant'),
        ),
        migrations.AddField(
            model_name='studentaddress',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='studentacademichistory',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_history', to='academics.academicyear', verbose_name='Academic Year'),
        ),
        migrations.AddField(
            model_name='studentacademichistory',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_history', to='academics.schoolclass', verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='studentacademichistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='studentacademichistory',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='studentacademichistory',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_history', to='academics.section', verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='studentacademichistory',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_history', to='students.student', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='studentacademichistory',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant'),
        ),
        migrations.AddField(
            model_name='studentacademichistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='academics.academicyear', verbose_name='Academic Year'),
        ),
        migrations.AddField(
            model_name='student',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.schoolclass', verbose_name='Current Class'),
        ),
        migrations.AddField(
            model_name='student',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.section', verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='student',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.stream', verbose_name='Stream'),
        ),
        migrations.AddField(
            model_name='student',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant'),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='System User Account'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='students.student', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddIndex(
            model_name='studentidentification',
            index=models.Index(fields=['aadhaar_number'], name='students_id_aadhaar_9d3448_idx'),
        ),
        migrations.AddIndex(
            model_name='studentidentification',
            index=models.Index(fields=['pan_number'], name='students_id_pan_num_a2b682_idx'),
        ),
        migrations.AddIndex(
            model_name='studentidentification',
            index=models.Index(fields=['passport_number'], name='students_id_passpor_85d582_idx'),
        ),
        migrations.AddIndex(
            model_name='studentdocument',
            index=models.Index(fields=['student', 'doc_type', 'is_current'], name='students_do_student_a84eff_idx'),
        ),
        migrations.AddIndex(
            model_name='studentdocument',
            index=models.Index(fields=['status', 'is_verified'], name='students_do_status_a1df32_idx'),
        ),
        migrations.AddIndex(
            model_name='studentdocument',
            index=models.Index(fields=['expiry_date'], name='students_do_expiry__4d137a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentdocument',
            unique_together={('student', 'doc_type', 'version')},
        ),
        migrations.AddIndex(
            model_name='studentaddress',
            index=models.Index(fields=['student', 'is_current'], name='students_ad_student_4b1e8b_idx'),
        ),
        migrations.AddIndex(
            model_name='studentaddress',
            index=models.Index(fields=['city', 'state'], name='students_ad_city_381c67_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentaddress',
            unique_together={('student', 'address_type')},
        ),
        migrations.AlterUniqueTogether(
            name='studentacademichistory',
            unique_together={('student', 'academic_year')},
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['admission_number'], name='students_st_admissi_321db4_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['roll_number'], name='students_st_roll_nu_6ff92b_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['personal_email'], name='students_st_persona_26bee1_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status'], name='students_st_status_5e2210_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['tenant', 'current_class'], name='students_st_tenant__5e940e_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['tenant', 'academic_year'], name='students_st_tenant__9952f2_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['created_at'], name='students_st_created_78a19f_idx'),
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['student', 'relation'], name='students_gu_student_c6c156_idx'),
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['is_primary'], name='students_gu_is_prim_9a9f6b_idx'),
        ),
        migrations.AddConstraint(
            model_name='guardian',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('student', 'is_primary'), name='unique_primary_guardian_per_student'),
        ),
        migrations.AddConstraint(
            model_name='guardian',
            constraint=models.UniqueConstraint(condition=models.Q(('is_emergency_contact', True)), fields=('student', 'is_emergency_contact'), name='unique_emergency_contact_per_student'),
        ),
    ]
