# Generated by Django 4.2.7 on 2025-12-13 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0002_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineapplication',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='onlineapplication',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='onlineapplication',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='admission.admissionprogram', verbose_name='Program'),
        ),
        migrations.AddField(
            model_name='onlineapplication',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant'),
        ),
        migrations.AddField(
            model_name='onlineapplication',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='meritlistentry',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merit_list_entries', to='admission.onlineapplication', verbose_name='Application'),
        ),
        migrations.AddField(
            model_name='meritlistentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='meritlistentry',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='meritlistentry',
            name='merit_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='admission.meritlist', verbose_name='Merit List'),
        ),
        migrations.AddField(
            model_name='meritlistentry',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant'),
        ),
        migrations.AddField(
            model_name='meritlistentry',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='meritlist',
            name='admission_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merit_lists', to='admission.admissioncycle', verbose_name='Admission Cycle'),
        ),
        migrations.AddField(
            model_name='meritlist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='meritlist',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='meritlist',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merit_lists', to='admission.admissionprogram', verbose_name='Program'),
        ),
        migrations.AddField(
            model_name='meritlist',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant'),
        ),
        migrations.AddField(
            model_name='meritlist',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='applicationlog',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='admission.onlineapplication', verbose_name='Application'),
        ),
        migrations.AddField(
            model_name='applicationlog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_logs', to=settings.AUTH_USER_MODEL, verbose_name='Performed By'),
        ),
        migrations.AddField(
            model_name='applicationlog',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='applicationlog',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant'),
        ),
        migrations.AddField(
            model_name='applicationlog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='applicationguardian',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='admission.onlineapplication', verbose_name='Application'),
        ),
        migrations.AddField(
            model_name='applicationguardian',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='applicationguardian',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='applicationguardian',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant'),
        ),
        migrations.AddField(
            model_name='applicationguardian',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admission.onlineapplication', verbose_name='Application'),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant'),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_application_docs', to=settings.AUTH_USER_MODEL, verbose_name='Verified By'),
        ),
        migrations.AddField(
            model_name='admissionstatistics',
            name='admission_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='admission.admissioncycle', verbose_name='Admission Cycle'),
        ),
        migrations.AddField(
            model_name='admissionstatistics',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='admissionstatistics',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='admissionstatistics',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='admission.admissionprogram', verbose_name='Program'),
        ),
        migrations.AddField(
            model_name='admissionstatistics',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant'),
        ),
        migrations.AddField(
            model_name='admissionstatistics',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='admissionprogram',
            name='admission_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='admission.admissioncycle', verbose_name='Admission Cycle'),
        ),
        migrations.AddField(
            model_name='admissionprogram',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='admissionprogram',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='admissionprogram',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant'),
        ),
        migrations.AddField(
            model_name='admissionprogram',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='admissionformconfig',
            name='admission_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_configs', to='admission.admissioncycle', verbose_name='Admission Cycle'),
        ),
        migrations.AddField(
            model_name='admissionformconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='admissionformconfig',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='admissionformconfig',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_configs', to='admission.admissionprogram', verbose_name='Program'),
        ),
        migrations.AddField(
            model_name='admissionformconfig',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant'),
        ),
        migrations.AddField(
            model_name='admissionformconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='admissioncycle',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_cycles', to='academics.academicyear', verbose_name='Academic Year'),
        ),
        migrations.AddField(
            model_name='admissioncycle',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='admissioncycle',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='admissioncycle',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant'),
        ),
        migrations.AddField(
            model_name='admissioncycle',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddIndex(
            model_name='onlineapplication',
            index=models.Index(fields=['application_number'], name='admission_o_applica_86a622_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineapplication',
            index=models.Index(fields=['email', 'admission_cycle'], name='admission_o_email_092650_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineapplication',
            index=models.Index(fields=['status', 'admission_cycle'], name='admission_o_status_8b92b6_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineapplication',
            index=models.Index(fields=['program', 'status'], name='admission_o_program_b8f1b2_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineapplication',
            index=models.Index(fields=['date_of_birth'], name='admission_o_date_of_a329bb_idx'),
        ),
        migrations.AddIndex(
            model_name='meritlistentry',
            index=models.Index(fields=['merit_list', 'rank'], name='admission_m_merit_l_d6272e_idx'),
        ),
        migrations.AddIndex(
            model_name='meritlistentry',
            index=models.Index(fields=['is_selected'], name='admission_m_is_sele_be3a18_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='meritlistentry',
            unique_together={('merit_list', 'application')},
        ),
        migrations.AddIndex(
            model_name='meritlist',
            index=models.Index(fields=['admission_cycle', 'program'], name='admission_m_admissi_873c0a_idx'),
        ),
        migrations.AddIndex(
            model_name='meritlist',
            index=models.Index(fields=['is_published'], name='admission_m_is_publ_1f2405_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='meritlist',
            unique_together={('admission_cycle', 'program', 'category')},
        ),
        migrations.AddIndex(
            model_name='applicationlog',
            index=models.Index(fields=['application', 'created_at'], name='admission_a_applica_d41a39_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationlog',
            index=models.Index(fields=['action'], name='admission_a_action_dc1282_idx'),
        ),
        migrations.AddConstraint(
            model_name='applicationguardian',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('application', 'is_primary'), name='unique_primary_guardian_per_application'),
        ),
        migrations.AddIndex(
            model_name='applicationdocument',
            index=models.Index(fields=['application', 'document_type'], name='admission_a_applica_be712c_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationdocument',
            index=models.Index(fields=['is_verified'], name='admission_a_is_veri_b9d33d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationdocument',
            unique_together={('application', 'document_type')},
        ),
        migrations.AddIndex(
            model_name='admissionstatistics',
            index=models.Index(fields=['admission_cycle', 'program'], name='admission_s_admissi_c75454_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='admissionstatistics',
            unique_together={('admission_cycle', 'program')},
        ),
        migrations.AddIndex(
            model_name='admissionprogram',
            index=models.Index(fields=['admission_cycle', 'is_active'], name='admission_p_admissi_8cae2e_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionprogram',
            index=models.Index(fields=['program_type'], name='admission_p_program_2da59a_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionprogram',
            index=models.Index(fields=['class_grade'], name='admission_p_class_g_5ac94a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='admissionprogram',
            unique_together={('admission_cycle', 'class_grade', 'stream')},
        ),
        migrations.AlterUniqueTogether(
            name='admissionformconfig',
            unique_together={('admission_cycle', 'program')},
        ),
        migrations.AddIndex(
            model_name='admissioncycle',
            index=models.Index(fields=['code', 'status'], name='admission_c_code_57e580_idx'),
        ),
        migrations.AddIndex(
            model_name='admissioncycle',
            index=models.Index(fields=['start_date', 'end_date'], name='admission_c_start_d_85afab_idx'),
        ),
        migrations.AddIndex(
            model_name='admissioncycle',
            index=models.Index(fields=['academic_year', 'status'], name='admission_c_academi_5d1605_idx'),
        ),
        migrations.AddIndex(
            model_name='admissioncycle',
            index=models.Index(fields=['school_level'], name='admission_c_school__f93c8e_idx'),
        ),
    ]
