# Generated by Django 4.2.7 on 2025-12-13 04:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('user_email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('user_display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('SOFT_DELETE', 'Soft Delete'), ('RESTORE', 'Restore'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('PASSWORD_CHANGE', 'Password Change'), ('PERMISSION_CHANGE', 'Permission Change'), ('TENANT_SWITCH', 'Tenant Switch'), ('BULK_OPERATION', 'Bulk Operation'), ('API_CALL', 'API Call')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='SUCCESS', max_length=20)),
                ('resource_type', models.CharField(db_index=True, max_length=100)),
                ('resource_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('resource_name', models.CharField(blank=True, max_length=500, null=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('previous_state', models.JSONField(blank=True, null=True)),
                ('new_state', models.JSONField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('request_method', models.CharField(blank=True, max_length=10, null=True)),
                ('request_path', models.CharField(blank=True, max_length=500, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('tenant_name', models.CharField(blank=True, max_length=200, null=True)),
                ('duration_ms', models.FloatField(blank=True, null=True)),
                ('object_uuid', models.CharField(blank=True, max_length=100, null=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'action'], name='audit_logs_timesta_05ea8c_idx'), models.Index(fields=['user_email', 'timestamp'], name='audit_logs_user_em_fbd03e_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_logs_resourc_bda8a6_idx'), models.Index(fields=['tenant_id', 'timestamp'], name='audit_logs_tenant__eb751d_idx'), models.Index(fields=['request_id'], name='audit_logs_request_298ea7_idx'), models.Index(fields=['session_id'], name='audit_logs_session_632f07_idx')],
            },
        ),
    ]
