# Generated by Django 4.2.7 on 2025-12-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialconfiguration',
            name='bank_accounts',
            field=models.JSONField(blank=True, default=list, verbose_name='Bank Accounts'),
        ),
        migrations.AlterField(
            model_name='financialconfiguration',
            name='payment_methods',
            field=models.JSONField(blank=True, default=list, verbose_name='Available Payment Methods'),
        ),
    ]
