# Generated by Django 4.2.7 on 2025-12-18 14:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0002_initial'),
        ('configuration', '0003_alter_financialconfiguration_bank_accounts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Universal ID')),
                ('data_signature', models.CharField(blank=True, editable=False, max_length=64, verbose_name='Data Integrity Signature')),
                ('encryption_version', models.CharField(default='v1', editable=False, max_length=10, verbose_name='Encryption Scheme Version')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation Timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last Modification Timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False indicates the record has been soft deleted', verbose_name='Active Status')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deletion Timestamp')),
                ('deletion_reason', models.TextField(blank=True, help_text='Mandatory for compliance: Reason for record deletion', null=True, verbose_name='Deletion Justification')),
                ('deletion_category', models.CharField(blank=True, choices=[('USER_REQUEST', 'User Request'), ('ADMIN_ACTION', 'Administrative Action'), ('SYSTEM_CLEANUP', 'System Cleanup'), ('COMPLIANCE', 'Compliance Requirement'), ('OTHER', 'Other')], max_length=50, null=True, verbose_name='Deletion Category')),
                ('request_count', models.PositiveIntegerField(default=0, verbose_name='API Request Count')),
                ('last_request_at', models.DateTimeField(blank=True, null=True, verbose_name='Last API Request')),
                ('rate_limit_key', models.CharField(blank=True, editable=False, max_length=100, verbose_name='Rate Limit Identifier')),
                ('academic_year_name', models.CharField(blank=True, max_length=100, verbose_name='Academic Year Name')),
                ('academic_year_start', models.DateField(blank=True, null=True, verbose_name='Academic Year Start')),
                ('academic_year_end', models.DateField(blank=True, null=True, verbose_name='Academic Year End')),
                ('grading_system_name', models.CharField(default='Standard Grading', max_length=100, verbose_name='Grading System Name')),
                ('pass_percentage', models.DecimalField(decimal_places=2, default=35.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Minimum Pass Percentage')),
                ('grace_marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Maximum Grace Marks')),
                ('min_attendance_percentage', models.DecimalField(decimal_places=2, default=75.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Minimum Attendance Percentage')),
                ('working_days_per_week', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Working Days Per Week')),
                ('periods_per_day', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Periods Per Day')),
                ('exam_types', models.TextField(blank=True, help_text='Comma-separated list of exam types', verbose_name='Exam Types')),
                ('practical_marks_weight', models.DecimalField(decimal_places=2, default=30.0, max_digits=5, verbose_name='Practical Marks Weight (%)')),
                ('theory_marks_weight', models.DecimalField(decimal_places=2, default=70.0, max_digits=5, verbose_name='Theory Marks Weight (%)')),
                ('promotion_conditions', models.TextField(blank=True, verbose_name='Promotion Conditions')),
                ('max_failed_subjects', models.PositiveIntegerField(default=2, verbose_name='Maximum Failed Subjects for Promotion')),
                ('term_start_date', models.DateField(blank=True, null=True, verbose_name='Term Start Date')),
                ('term_end_date', models.DateField(blank=True, null=True, verbose_name='Term End Date')),
                ('chart_field', models.CharField(choices=[('BAR', 'Bar Chart'), ('PIE', 'Pie Chart'), ('LINE', 'Line Chart'), ('TABLE', 'Data Table')], default='TABLE', max_length=20, verbose_name='Chart Type')),
                ('late_fee_percentage', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Late Fee Percentage')),
                ('late_fee_grace_days', models.PositiveIntegerField(default=10, verbose_name='Late Fee Grace Period (Days)')),
            ],
            options={
                'verbose_name': 'Academic Configuration',
                'verbose_name_plural': 'Academic Configurations',
                'db_table': 'configuration_academic',
            },
        ),
        migrations.RemoveField(
            model_name='appearanceconfiguration',
            name='dashboard_widgets',
        ),
        migrations.RemoveField(
            model_name='backupconfiguration',
            name='storage_config',
        ),
        migrations.RemoveField(
            model_name='financialconfiguration',
            name='bank_accounts',
        ),
        migrations.RemoveField(
            model_name='financialconfiguration',
            name='default_bank_account',
        ),
        migrations.RemoveField(
            model_name='financialconfiguration',
            name='payment_gateway_config',
        ),
        migrations.RemoveField(
            model_name='integrationconfiguration',
            name='auth_config',
        ),
        migrations.RemoveField(
            model_name='notificationconfiguration',
            name='default_templates',
        ),
        migrations.RemoveField(
            model_name='notificationconfiguration',
            name='push_config',
        ),
        migrations.RemoveField(
            model_name='notificationconfiguration',
            name='template_variables',
        ),
        migrations.AddField(
            model_name='appearanceconfiguration',
            name='chart_field',
            field=models.CharField(choices=[('BAR', 'Bar Chart'), ('PIE', 'Pie Chart'), ('LINE', 'Line Chart'), ('TABLE', 'Data Table')], default='TABLE', max_length=20, verbose_name='Chart Type'),
        ),
        migrations.AddField(
            model_name='backupconfiguration',
            name='chart_field',
            field=models.CharField(choices=[('BAR', 'Bar Chart'), ('PIE', 'Pie Chart'), ('LINE', 'Line Chart'), ('TABLE', 'Data Table')], default='TABLE', max_length=20, verbose_name='Chart Type'),
        ),
        migrations.AddField(
            model_name='financialconfiguration',
            name='bank_accounts_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Bank Accounts'),
        ),
        migrations.AddField(
            model_name='financialconfiguration',
            name='chart_field',
            field=models.CharField(choices=[('BAR', 'Bar Chart'), ('PIE', 'Pie Chart'), ('LINE', 'Line Chart'), ('TABLE', 'Data Table')], default='TABLE', max_length=20, verbose_name='Chart Type'),
        ),
        migrations.AddField(
            model_name='financialconfiguration',
            name='default_bank_account_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Default Bank Account Name'),
        ),
        migrations.AddField(
            model_name='financialconfiguration',
            name='payment_gateway_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Payment Gateway Name'),
        ),
        migrations.AddField(
            model_name='integrationconfiguration',
            name='chart_field',
            field=models.CharField(choices=[('BAR', 'Bar Chart'), ('PIE', 'Pie Chart'), ('LINE', 'Line Chart'), ('TABLE', 'Data Table')], default='TABLE', max_length=20, verbose_name='Chart Type'),
        ),
        migrations.AddField(
            model_name='notificationconfiguration',
            name='chart_field',
            field=models.CharField(choices=[('BAR', 'Bar Chart'), ('PIE', 'Pie Chart'), ('LINE', 'Line Chart'), ('TABLE', 'Data Table')], default='TABLE', max_length=20, verbose_name='Chart Type'),
        ),
        migrations.AddField(
            model_name='notificationconfiguration',
            name='default_email_template',
            field=models.TextField(blank=True, verbose_name='Default Email Template'),
        ),
        migrations.AddField(
            model_name='notificationconfiguration',
            name='default_sms_template',
            field=models.TextField(blank=True, verbose_name='Default SMS Template'),
        ),
        migrations.AddField(
            model_name='securityconfiguration',
            name='chart_field',
            field=models.CharField(choices=[('BAR', 'Bar Chart'), ('PIE', 'Pie Chart'), ('LINE', 'Line Chart'), ('TABLE', 'Data Table')], default='TABLE', max_length=20, verbose_name='Chart Type'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='chart_field',
            field=models.CharField(choices=[('TABLE', 'Table'), ('BAR', 'Bar Chart'), ('PIE', 'Pie Chart'), ('LINE', 'Line Chart')], default='TABLE', max_length=20, verbose_name='Chart Type'),
        ),
        migrations.AlterField(
            model_name='backupconfiguration',
            name='excluded_tables',
            field=models.TextField(blank=True, help_text='Comma-separated list of table names', verbose_name='Excluded Database Tables'),
        ),
        migrations.AlterField(
            model_name='backupconfiguration',
            name='notification_emails',
            field=models.TextField(blank=True, help_text='Comma-separated list of email addresses', verbose_name='Notification Emails'),
        ),
        migrations.AlterField(
            model_name='financialconfiguration',
            name='payment_methods',
            field=models.TextField(blank=True, help_text='Comma-separated list of payment methods', verbose_name='Available Payment Methods'),
        ),
        migrations.AlterField(
            model_name='integrationconfiguration',
            name='api_keys',
            field=models.TextField(blank=True, verbose_name='API Keys and Secrets'),
        ),
        migrations.AlterField(
            model_name='integrationconfiguration',
            name='config_data',
            field=models.TextField(blank=True, verbose_name='Configuration Data'),
        ),
        migrations.AlterField(
            model_name='integrationconfiguration',
            name='endpoints',
            field=models.TextField(blank=True, verbose_name='API Endpoints'),
        ),
        migrations.AlterField(
            model_name='integrationconfiguration',
            name='webhook_events',
            field=models.TextField(blank=True, verbose_name='Webhook Events'),
        ),
        migrations.AlterField(
            model_name='notificationconfiguration',
            name='default_notification_channels',
            field=models.TextField(blank=True, help_text='Comma-separated list of channels: EMAIL,SMS,PUSH,WHATSAPP', verbose_name='Default Notification Channels'),
        ),
        migrations.AlterField(
            model_name='securityconfiguration',
            name='allowed_2fa_methods',
            field=models.TextField(blank=True, help_text='Comma-separated list of 2FA methods', verbose_name='Allowed 2FA Methods'),
        ),
        migrations.AlterField(
            model_name='securityconfiguration',
            name='ip_blacklist',
            field=models.TextField(blank=True, help_text='Comma-separated list of blocked IP addresses', verbose_name='IP Blacklist'),
        ),
        migrations.AlterField(
            model_name='securityconfiguration',
            name='ip_whitelist',
            field=models.TextField(blank=True, help_text='Comma-separated list of allowed IP addresses', verbose_name='IP Whitelist'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='choices',
            field=models.TextField(blank=True, help_text='Comma-separated list of choices for CHOICE and MULTI_CHOICE types', verbose_name='Available Choices'),
        ),
        migrations.AddIndex(
            model_name='appearanceconfiguration',
            index=models.Index(fields=['chart_field'], name='configurati_chart_f_def17f_idx'),
        ),
        migrations.AddIndex(
            model_name='backupconfiguration',
            index=models.Index(fields=['chart_field'], name='configurati_chart_f_1ee8fe_idx'),
        ),
        migrations.AddIndex(
            model_name='financialconfiguration',
            index=models.Index(fields=['chart_field'], name='configurati_chart_f_fa38eb_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationconfiguration',
            index=models.Index(fields=['chart_field'], name='configurati_chart_f_913646_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationconfiguration',
            index=models.Index(fields=['chart_field'], name='configurati_chart_f_5fb0a1_idx'),
        ),
        migrations.AddIndex(
            model_name='securityconfiguration',
            index=models.Index(fields=['chart_field'], name='configurati_chart_f_662930_idx'),
        ),
        migrations.AddIndex(
            model_name='systemsetting',
            index=models.Index(fields=['chart_field'], name='configurati_chart_f_bc88c9_idx'),
        ),
        migrations.AddField(
            model_name='academicconfiguration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='academicconfiguration',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='academicconfiguration',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant'),
        ),
        migrations.AddField(
            model_name='academicconfiguration',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddIndex(
            model_name='academicconfiguration',
            index=models.Index(fields=['academic_year_name'], name='configurati_academi_9d718d_idx'),
        ),
        migrations.AddIndex(
            model_name='academicconfiguration',
            index=models.Index(fields=['chart_field'], name='configurati_chart_f_2e05aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='academicconfiguration',
            unique_together={('tenant',)},
        ),
    ]
