# Generated by Django 4.2.7 on 2025-12-13 04:15

import django.core.validators
from django.db import migrations, models
import django_tenants.postgresql_backend.base
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Universal ID')),
                ('data_signature', models.CharField(blank=True, editable=False, max_length=64, verbose_name='Data Integrity Signature')),
                ('encryption_version', models.CharField(default='v1', editable=False, max_length=10, verbose_name='Encryption Scheme Version')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation Timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last Modification Timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False indicates the record has been soft deleted', verbose_name='Active Status')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deletion Timestamp')),
                ('deletion_reason', models.TextField(blank=True, help_text='Mandatory for compliance: Reason for record deletion', null=True, verbose_name='Deletion Justification')),
                ('deletion_category', models.CharField(blank=True, choices=[('USER_REQUEST', 'User Request'), ('ADMIN_ACTION', 'Administrative Action'), ('SYSTEM_CLEANUP', 'System Cleanup'), ('COMPLIANCE', 'Compliance Requirement'), ('OTHER', 'Other')], max_length=50, null=True, verbose_name='Deletion Category')),
                ('request_count', models.PositiveIntegerField(default=0, verbose_name='API Request Count')),
                ('last_request_at', models.DateTimeField(blank=True, null=True, verbose_name='Last API Request')),
                ('rate_limit_key', models.CharField(blank=True, editable=False, max_length=100, verbose_name='Rate Limit Identifier')),
                ('is_primary', models.BooleanField(db_index=True, default=False, help_text='Designates the primary domain for this tenant', verbose_name='Primary Domain')),
                ('ssl_enabled', models.BooleanField(default=True, help_text='Enable SSL for this domain', verbose_name='SSL Enabled')),
                ('is_verified', models.BooleanField(default=False, help_text='Domain ownership has been verified', verbose_name='Domain Verified')),
                ('verification_token', models.CharField(blank=True, editable=False, max_length=64, verbose_name='Domain Verification Token')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
                'db_table': 'tenant_domains',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Universal ID')),
                ('data_signature', models.CharField(blank=True, editable=False, max_length=64, verbose_name='Data Integrity Signature')),
                ('encryption_version', models.CharField(default='v1', editable=False, max_length=10, verbose_name='Encryption Scheme Version')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation Timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last Modification Timestamp')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deletion Timestamp')),
                ('deletion_reason', models.TextField(blank=True, help_text='Mandatory for compliance: Reason for record deletion', null=True, verbose_name='Deletion Justification')),
                ('deletion_category', models.CharField(blank=True, choices=[('USER_REQUEST', 'User Request'), ('ADMIN_ACTION', 'Administrative Action'), ('SYSTEM_CLEANUP', 'System Cleanup'), ('COMPLIANCE', 'Compliance Requirement'), ('OTHER', 'Other')], max_length=50, null=True, verbose_name='Deletion Category')),
                ('request_count', models.PositiveIntegerField(default=0, verbose_name='API Request Count')),
                ('last_request_at', models.DateTimeField(blank=True, null=True, verbose_name='Last API Request')),
                ('rate_limit_key', models.CharField(blank=True, editable=False, max_length=100, verbose_name='Rate Limit Identifier')),
                ('name', models.CharField(help_text='Legal name of the institution/organization', max_length=255, verbose_name='Organization Name')),
                ('display_name', models.CharField(help_text='Public-facing name for the institution', max_length=255, verbose_name='Display Name')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('trial', 'Trial'), ('expired', 'Expired')], db_index=True, default='trial', max_length=20, verbose_name='Tenant Status')),
                ('plan', models.CharField(choices=[('basic', 'Basic'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='basic', max_length=20, verbose_name='Subscription Plan')),
                ('max_users', models.PositiveIntegerField(default=10, help_text='Maximum number of active users allowed', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Maximum Users')),
                ('max_storage_mb', models.PositiveIntegerField(default=1024, help_text='Maximum storage space in megabytes', verbose_name='Storage Limit (MB)')),
                ('contact_email', models.EmailField(help_text='Primary contact email for administrative communications', max_length=254, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(blank=True, help_text='Primary contact phone number', max_length=20, null=True, verbose_name='Contact Phone')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this tenant can access the system', verbose_name='Active Status')),
                ('force_password_reset', models.BooleanField(default=False, help_text='Require all users to reset their passwords on next login', verbose_name='Force Password Reset')),
                ('mfa_required', models.BooleanField(default=False, help_text='Require multi-factor authentication for all users', verbose_name='MFA Required')),
                ('password_policy', models.JSONField(default=dict, help_text='Custom password policy configuration', verbose_name='Password Policy')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Trial End Date')),
                ('subscription_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Subscription End Date')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'tenants',
            },
        ),
        migrations.CreateModel(
            name='TenantConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Universal ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation Timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last Modification Timestamp')),
                ('academic_year', models.CharField(default='2024-2025', max_length=20, verbose_name='Current Academic Year')),
                ('timezone', models.CharField(default='UTC', max_length=50, verbose_name='Default Timezone')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='Default Language')),
                ('currency', models.CharField(default='INR', max_length=3, verbose_name='Default Currency')),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=20, verbose_name='Date Format')),
                ('session_timeout', models.PositiveIntegerField(default=30, verbose_name='Session Timeout (minutes)')),
                ('max_login_attempts', models.PositiveIntegerField(default=5, verbose_name='Maximum Login Attempts')),
                ('password_expiry_days', models.PositiveIntegerField(default=90, verbose_name='Password Expiry (days)')),
                ('enable_library', models.BooleanField(default=True, verbose_name='Enable Library Module')),
                ('enable_finance', models.BooleanField(default=True, verbose_name='Enable Finance Module')),
                ('enable_inventory', models.BooleanField(default=True, verbose_name='Enable Inventory Module')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenant_logos/', verbose_name='Organization Logo')),
                ('primary_color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Primary Brand Color')),
                ('secondary_color', models.CharField(default='#1E40AF', max_length=7, verbose_name='Secondary Brand Color')),
            ],
            options={
                'verbose_name': 'Tenant Configuration',
                'verbose_name_plural': 'Tenant Configurations',
                'db_table': 'tenant_configurations',
            },
        ),
    ]
