# Generated by Django 4.2.7 on 2025-12-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='category',
            field=models.CharField(choices=[('TEACHING', 'Teaching Staff'), ('PROFESSOR', 'Professor'), ('ASSOCIATE_PROFESSOR', 'Associate Professor'), ('ASSISTANT_PROFESSOR', 'Assistant Professor'), ('LECTURER', 'Lecturer'), ('GUEST_FACULTY', 'Guest / Visiting Faculty'), ('LAB_INSTRUCTOR', 'Lab Instructor'), ('TUTOR', 'Tutor / Academic Coach'), ('HOD', 'Head of Department'), ('ACADEMIC_COORDINATOR', 'Academic Coordinator'), ('EXAM_CONTROLLER', 'Controller of Examinations'), ('RESEARCH_GUIDE', 'Research Guide / Supervisor'), ('ADMINISTRATIVE', 'Administrative Staff'), ('PRINCIPAL', 'Principal'), ('VICE_PRINCIPAL', 'Vice Principal'), ('DEAN', 'Dean'), ('REGISTRAR', 'Registrar'), ('OFFICE_SUPERINTENDENT', 'Office Superintendent'), ('CLERK', 'Clerk'), ('ACCOUNTANT', 'Accountant'), ('HR', 'Human Resource Officer'), ('ADMISSION_OFFICER', 'Admission Officer'), ('PLACEMENT_OFFICER', 'Placement Officer'), ('COUNSELLOR', 'Student Counsellor'), ('LIBRARIAN', 'Librarian'), ('LIBRARY_ASSISTANT', 'Library Assistant'), ('SPORTS_COACH', 'Sports Coach'), ('TRANSPORT_MANAGER', 'Transport Manager'), ('IT_ADMIN', 'IT Administrator'), ('SYSTEM_ADMIN', 'System Administrator'), ('NETWORK_ENGINEER', 'Network Engineer'), ('LAB_TECHNICIAN', 'Lab Technician'), ('ERP_ADMIN', 'ERP Administrator'), ('SUPPORT', 'Support Staff'), ('PEON', 'Peon / Office Assistant'), ('SECURITY', 'Security Staff'), ('HOUSEKEEPING', 'Housekeeping Staff'), ('ELECTRICIAN', 'Electrician'), ('PLUMBER', 'Plumber'), ('DRIVER', 'Driver'), ('WARDEN', 'Hostel Warden'), ('MESS_STAFF', 'Mess / Canteen Staff')], max_length=50, verbose_name='Staff Category'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='experience_required',
            field=models.CharField(blank=True, choices=[(0, 'Fresher'), (1, '1 Year'), (2, '2 Years'), (3, '3 Years'), (5, '5+ Years'), (10, '10+ Years')], max_length=50, verbose_name='Experience Required'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='qualifications',
            field=models.CharField(blank=True, choices=[('DIPLOMA', 'Diploma'), ('BACHELOR', 'Bachelor’s Degree'), ('MASTER', 'Master’s Degree'), ('M_PHIL', 'M.Phil'), ('PHD', 'Ph.D'), ('B_ED', 'B.Ed'), ('M_ED', 'M.Ed'), ('NET', 'NET Qualified'), ('SET', 'SET Qualified'), ('CTET', 'CTET Qualified'), ('OTHER', 'Other')], max_length=50, verbose_name='Required Qualification'),
        ),
    ]
