# Generated by Django 4.2.7 on 2025-12-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_designation_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='code',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='Designation Code'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='grade',
            field=models.CharField(blank=True, choices=[('A+', 'Grade A+ (Senior Most)'), ('A', 'Grade A'), ('B+', 'Grade B+'), ('B', 'Grade B'), ('C+', 'Grade C+'), ('C', 'Grade C'), ('D', 'Grade D (Entry Level)'), ('ADM_1', 'Admin Level 1'), ('ADM_2', 'Admin Level 2'), ('ADM_3', 'Admin Level 3'), ('SUP_1', 'Support Level 1'), ('SUP_2', 'Support Level 2'), ('SUP_3', 'Support Level 3')], max_length=20, verbose_name='Grade Level'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='title',
            field=models.CharField(choices=[('PROFESSOR', 'Professor'), ('ASSOCIATE_PROFESSOR', 'Associate Professor'), ('ASSISTANT_PROFESSOR', 'Assistant Professor'), ('LECTURER', 'Lecturer'), ('GUEST_FACULTY', 'Guest Faculty'), ('LAB_INSTRUCTOR', 'Lab Instructor'), ('TUTOR', 'Tutor / Academic Coach'), ('HOD', 'Head of Department'), ('DEAN', 'Dean'), ('PRINCIPAL', 'Principal'), ('VICE_PRINCIPAL', 'Vice Principal'), ('REGISTRAR', 'Registrar'), ('ADMIN_OFFICER', 'Administrative Officer'), ('OFFICE_SUPERINTENDENT', 'Office Superintendent'), ('CLERK', 'Clerk'), ('ACCOUNTANT', 'Accountant'), ('HR_OFFICER', 'Human Resource Officer'), ('ADMISSION_OFFICER', 'Admission Officer'), ('PLACEMENT_OFFICER', 'Placement Officer'), ('COUNSELLOR', 'Student Counsellor'), ('LIBRARIAN', 'Librarian'), ('IT_ADMIN', 'IT Administrator'), ('SYSTEM_ADMIN', 'System Administrator'), ('NETWORK_ENGINEER', 'Network Engineer'), ('LAB_TECHNICIAN', 'Lab Technician'), ('WARDEN', 'Hostel Warden'), ('DRIVER', 'Driver'), ('SECURITY', 'Security Staff'), ('PEON', 'Office Assistant'), ('HOUSEKEEPING', 'Housekeeping Staff')], max_length=50, verbose_name='Designation Title'),
        ),
    ]
