# Generated by Django 4.2.7 on 2025-12-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_designation_code_alter_designation_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='experience_required',
            field=models.IntegerField(blank=True, choices=[(0, 'Fresher'), (1, '1 Year'), (2, '2 Years'), (3, '3 Years'), (5, '5+ Years'), (10, '10+ Years')], null=True, verbose_name='Experience Required (Years)'),
        ),
    ]
