# Generated by Django 4.2.7 on 2025-12-16 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0002_initial'),
        ('hr', '0005_alter_designation_experience_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='qualifications',
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Universal ID')),
                ('data_signature', models.CharField(blank=True, editable=False, max_length=64, verbose_name='Data Integrity Signature')),
                ('encryption_version', models.CharField(default='v1', editable=False, max_length=10, verbose_name='Encryption Scheme Version')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation Timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last Modification Timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False indicates the record has been soft deleted', verbose_name='Active Status')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deletion Timestamp')),
                ('deletion_reason', models.TextField(blank=True, help_text='Mandatory for compliance: Reason for record deletion', null=True, verbose_name='Deletion Justification')),
                ('deletion_category', models.CharField(blank=True, choices=[('USER_REQUEST', 'User Request'), ('ADMIN_ACTION', 'Administrative Action'), ('SYSTEM_CLEANUP', 'System Cleanup'), ('COMPLIANCE', 'Compliance Requirement'), ('OTHER', 'Other')], max_length=50, null=True, verbose_name='Deletion Category')),
                ('request_count', models.PositiveIntegerField(default=0, verbose_name='API Request Count')),
                ('last_request_at', models.DateTimeField(blank=True, null=True, verbose_name='Last API Request')),
                ('rate_limit_key', models.CharField(blank=True, editable=False, max_length=100, verbose_name='Rate Limit Identifier')),
                ('degree', models.CharField(choices=[('DIPLOMA', 'Diploma'), ('BACHELOR', 'Bachelor’s Degree'), ('MASTER', 'Master’s Degree'), ('M_PHIL', 'M.Phil'), ('PHD', 'Ph.D'), ('B_ED', 'B.Ed'), ('M_ED', 'M.Ed'), ('NET', 'NET Qualified'), ('SET', 'SET Qualified'), ('CTET', 'CTET Qualified'), ('OTHER', 'Other')], max_length=50, verbose_name='Degree')),
                ('specialization', models.CharField(blank=True, max_length=100, verbose_name='Specialization')),
                ('institution', models.CharField(blank=True, max_length=150, verbose_name='Institution')),
                ('year', models.DateField(blank=True, null=True, verbose_name='Year of Passing')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='designation',
            name='qualifications',
            field=models.ManyToManyField(blank=True, to='hr.qualification', verbose_name='Required Qualifications'),
        ),
        migrations.AddField(
            model_name='staff',
            name='qualifications',
            field=models.ManyToManyField(blank=True, to='hr.qualification', verbose_name='Required Qualifications'),
        ),
        migrations.AddIndex(
            model_name='qualification',
            index=models.Index(fields=['tenant', 'is_active', 'created_at'], name='hr_qualific_tenant__6da3d9_idx'),
        ),
        migrations.AddIndex(
            model_name='qualification',
            index=models.Index(fields=['tenant', 'is_active', 'updated_at'], name='hr_qualific_tenant__2323a8_idx'),
        ),
        migrations.AddIndex(
            model_name='qualification',
            index=models.Index(fields=['created_by', 'tenant', 'created_at'], name='hr_qualific_created_7d06fa_idx'),
        ),
    ]
