# Generated by Django 4.2.7 on 2025-12-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_remove_designation_qualifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancereview',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='allowances',
            field=models.JSONField(blank=True, default=dict, verbose_name='Allowances'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='deductions',
            field=models.JSONField(blank=True, default=dict, verbose_name='Deductions'),
        ),
    ]
