# Generated by Django 4.2.7 on 2025-12-16 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_performancereview_status_alter_payroll_allowances_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmenthistory',
            name='details',
        ),
    ]
