# Generated by Django 4.2.7 on 2025-12-18 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='False indicates the record has been soft deleted', verbose_name='Active Status'),
        ),
    ]
