# Generated by Django 4.2.7 on 2025-12-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exam_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultstatistics',
            name='grade_distribution',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Grade Distribution'),
        ),
        migrations.AlterField(
            model_name='resultstatistics',
            name='subject_performance',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Subject Performance'),
        ),
    ]
