# Generated by Django 4.2.7 on 2025-12-13 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('tenants', '0002_initial'),
        ('analytics', '0001_initial'),
        ('academics', '0002_initial'),
        ('students', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentperformanceanalytics',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='studentperformanceanalytics',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='studentperformanceanalytics',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_analytics', to='students.student', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='studentperformanceanalytics',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant'),
        ),
        migrations.AddField(
            model_name='studentperformanceanalytics',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='reportexecution',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='reportexecution',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='reportexecution',
            name='executed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_executions', to=settings.AUTH_USER_MODEL, verbose_name='Executed By'),
        ),
        migrations.AddField(
            model_name='reportexecution',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='analytics.report', verbose_name='Report'),
        ),
        migrations.AddField(
            model_name='reportexecution',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant'),
        ),
        migrations.AddField(
            model_name='reportexecution',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='report',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='report',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant'),
        ),
        migrations.AddField(
            model_name='report',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='predictivemodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='predictivemodel',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='predictivemodel',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant'),
        ),
        migrations.AddField(
            model_name='predictivemodel',
            name='training_data_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictive_models', to='analytics.datasource', verbose_name='Training Data Source'),
        ),
        migrations.AddField(
            model_name='predictivemodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='kpivalue',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear', verbose_name='Academic Year'),
        ),
        migrations.AddField(
            model_name='kpivalue',
            name='class_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.schoolclass', verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='kpivalue',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='kpivalue',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='kpivalue',
            name='kpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_values', to='analytics.kpi', verbose_name='KPI'),
        ),
        migrations.AddField(
            model_name='kpivalue',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.subject', verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='kpivalue',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant'),
        ),
        migrations.AddField(
            model_name='kpivalue',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='data_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='analytics.datasource', verbose_name='Data Source'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='institutionalanalytics',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutional_analytics', to='academics.academicyear', verbose_name='Academic Year'),
        ),
        migrations.AddField(
            model_name='institutionalanalytics',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='institutionalanalytics',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='institutionalanalytics',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant'),
        ),
        migrations.AddField(
            model_name='institutionalanalytics',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='analytics.dashboard', verbose_name='Dashboard'),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.datasource', verbose_name='Data Source'),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='kpi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.kpi', verbose_name='KPI'),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant'),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='auditpattern',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='auditpattern',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant'),
        ),
        migrations.AddField(
            model_name='auditpattern',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='auditmetricvalue',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='auditmetricvalue',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='analytics.auditmetric'),
        ),
        migrations.AddField(
            model_name='auditmetricvalue',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='auditmetricvalue',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='auditmetric',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='auditmetric',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant'),
        ),
        migrations.AddField(
            model_name='auditmetric',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='auditdashboard',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='auditdashboard',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_dashboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditdashboard',
            name='shared_with_groups',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
        migrations.AddField(
            model_name='auditdashboard',
            name='shared_with_users',
            field=models.ManyToManyField(blank=True, related_name='shared_dashboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditdashboard',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant'),
        ),
        migrations.AddField(
            model_name='auditdashboard',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='auditanalysisreport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='auditanalysisreport',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_audit_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditanalysisreport',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant'),
        ),
        migrations.AddField(
            model_name='auditanalysisreport',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='auditalert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditalert',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditalert',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='auditalert',
            name='pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='analytics.auditpattern'),
        ),
        migrations.AddField(
            model_name='auditalert',
            name='related_logs',
            field=models.ManyToManyField(blank=True, to='core.auditlog'),
        ),
        migrations.AddField(
            model_name='auditalert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditalert',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant'),
        ),
        migrations.AddField(
            model_name='auditalert',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddIndex(
            model_name='studentperformanceanalytics',
            index=models.Index(fields=['student', 'academic_year'], name='analytics_s_student_57490d_idx'),
        ),
        migrations.AddIndex(
            model_name='studentperformanceanalytics',
            index=models.Index(fields=['overall_percentage', 'class_rank'], name='analytics_s_overall_614ead_idx'),
        ),
        migrations.AddIndex(
            model_name='studentperformanceanalytics',
            index=models.Index(fields=['at_risk_score'], name='analytics_s_at_risk_5f8011_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentperformanceanalytics',
            unique_together={('student', 'academic_year')},
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['report', 'started_at'], name='analytics_r_report__be32b5_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['executed_by', 'status'], name='analytics_r_execute_747e37_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['status', 'completed_at'], name='analytics_r_status_b12314_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type', 'is_active'], name='analytics_r_report__51f9a0_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['access_level', 'is_template'], name='analytics_r_access__47e031_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['is_scheduled', 'schedule_frequency'], name='analytics_r_is_sche_fed38a_idx'),
        ),
        migrations.AddIndex(
            model_name='predictivemodel',
            index=models.Index(fields=['model_type', 'status'], name='analytics_p_model_t_dba4c5_idx'),
        ),
        migrations.AddIndex(
            model_name='predictivemodel',
            index=models.Index(fields=['algorithm', 'status'], name='analytics_p_algorit_eab886_idx'),
        ),
        migrations.AddIndex(
            model_name='predictivemodel',
            index=models.Index(fields=['status', 'trained_at'], name='analytics_p_status_3bb756_idx'),
        ),
        migrations.AddIndex(
            model_name='kpivalue',
            index=models.Index(fields=['kpi', 'period_end'], name='analytics_k_kpi_id_4388b0_idx'),
        ),
        migrations.AddIndex(
            model_name='kpivalue',
            index=models.Index(fields=['period_start', 'period_end'], name='analytics_k_period__a17478_idx'),
        ),
        migrations.AddIndex(
            model_name='kpivalue',
            index=models.Index(fields=['academic_year', 'class_name'], name='analytics_k_academi_82f9eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kpivalue',
            unique_together={('kpi', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='kpi',
            index=models.Index(fields=['code', 'is_active'], name='analytics_k_code_a27cee_idx'),
        ),
        migrations.AddIndex(
            model_name='kpi',
            index=models.Index(fields=['category', 'calculation_frequency'], name='analytics_k_categor_38284d_idx'),
        ),
        migrations.AddIndex(
            model_name='kpi',
            index=models.Index(fields=['is_active', 'last_calculated'], name='analytics_k_is_acti_df0161_idx'),
        ),
        migrations.AddIndex(
            model_name='datasource',
            index=models.Index(fields=['source_type', 'status'], name='analytics_d_source__8a2268_idx'),
        ),
        migrations.AddIndex(
            model_name='datasource',
            index=models.Index(fields=['status', 'last_sync'], name='analytics_d_status_6e0302_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardwidget',
            index=models.Index(fields=['dashboard', 'widget_type'], name='analytics_d_dashboa_f92872_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardwidget',
            index=models.Index(fields=['widget_type', 'chart_type'], name='analytics_d_widget__996b96_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['is_active', 'is_public'], name='analytics_d_is_acti_def97c_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['layout_type', 'is_template'], name='analytics_d_layout__fa8596_idx'),
        ),
        migrations.AddIndex(
            model_name='auditpattern',
            index=models.Index(fields=['pattern_type', 'severity'], name='analytics_a_pattern_13b04a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditpattern',
            index=models.Index(fields=['is_active', 'last_detected'], name='analytics_a_is_acti_2a0704_idx'),
        ),
        migrations.AddIndex(
            model_name='auditmetricvalue',
            index=models.Index(fields=['metric', 'timestamp'], name='analytics_a_metric__a4a230_idx'),
        ),
        migrations.AddIndex(
            model_name='auditmetricvalue',
            index=models.Index(fields=['tenant', 'metric', 'timestamp'], name='analytics_a_tenant__b0cdfe_idx'),
        ),
        migrations.AddIndex(
            model_name='auditmetricvalue',
            index=models.Index(fields=['period_type', 'timestamp'], name='analytics_a_period__9a51bb_idx'),
        ),
        migrations.AddIndex(
            model_name='auditmetric',
            index=models.Index(fields=['metric_type', 'calculation_schedule'], name='analytics_a_metric__8f4176_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='auditdashboard',
            unique_together={('tenant', 'owner', 'name')},
        ),
        migrations.AddIndex(
            model_name='auditanalysisreport',
            index=models.Index(fields=['tenant', 'report_type', 'created_at'], name='analytics_a_tenant__d4af88_idx'),
        ),
        migrations.AddIndex(
            model_name='auditanalysisreport',
            index=models.Index(fields=['status', 'created_at'], name='analytics_a_status_ee6f27_idx'),
        ),
        migrations.AddIndex(
            model_name='auditanalysisreport',
            index=models.Index(fields=['generated_by', 'created_at'], name='analytics_a_generat_7f58c1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditalert',
            index=models.Index(fields=['status', 'severity'], name='analytics_a_status_7678b1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditalert',
            index=models.Index(fields=['assigned_to', 'status'], name='analytics_a_assigne_b3db14_idx'),
        ),
        migrations.AddIndex(
            model_name='auditalert',
            index=models.Index(fields=['pattern', 'created_at'], name='analytics_a_pattern_67009a_idx'),
        ),
    ]
