# Generated by Django 4.2.7 on 2025-12-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dashboard Configuration'),
        ),
    ]
