# Generated by Django 4.2.7 on 2025-12-18 08:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0003_alter_dashboard_config'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KPI',
            new_name='KPIModel',
        ),
    ]
