# Generated by Django 4.2.7 on 2025-12-18 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0004_rename_kpi_kpimodel'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dashboardwidget',
            name='analytics_d_widget__996b96_idx',
        ),
        migrations.RemoveField(
            model_name='auditanalysisreport',
            name='filters',
        ),
        migrations.RemoveField(
            model_name='auditpattern',
            name='recommended_actions',
        ),
        migrations.RemoveField(
            model_name='dashboardwidget',
            name='chart_type',
        ),
        migrations.RemoveField(
            model_name='kpimodel',
            name='chart_type',
        ),
        migrations.AddField(
            model_name='auditalert',
            name='chart_config',
            field=models.JSONField(blank=True, default=dict, help_text='JSON configuration for visualization', verbose_name='Chart Configuration'),
        ),
        migrations.AddField(
            model_name='auditanalysisreport',
            name='chart_config',
            field=models.JSONField(blank=True, default=dict, help_text='JSON configuration for visualization', verbose_name='Chart Configuration'),
        ),
        migrations.AddField(
            model_name='auditanalysisreport',
            name='filter_type',
            field=models.CharField(choices=[('ALL', 'All Activities'), ('LOGIN_ONLY', 'Login Activities'), ('SECURITY_EVENTS', 'Security Events'), ('DATA_CHANGES', 'Data Changes'), ('FAILED_ACTIONS', 'Failed Actions'), ('USER_SPECIFIC', 'Specific User'), ('TENANT_WIDE', 'Tenant Wide'), ('COMPLIANCE_ONLY', 'Compliance Events'), ('CUSTOM', 'Custom Filter')], default='ALL', max_length=30, verbose_name='Filter Type'),
        ),
        migrations.AddField(
            model_name='auditdashboard',
            name='chart_config',
            field=models.JSONField(blank=True, default=dict, help_text='JSON configuration for visualization', verbose_name='Chart Configuration'),
        ),
        migrations.AddField(
            model_name='auditmetric',
            name='chart_config',
            field=models.JSONField(blank=True, default=dict, help_text='JSON configuration for visualization', verbose_name='Chart Configuration'),
        ),
        migrations.AddField(
            model_name='auditpattern',
            name='chart_config',
            field=models.JSONField(blank=True, default=dict, help_text='JSON configuration for visualization', verbose_name='Chart Configuration'),
        ),
        migrations.AddField(
            model_name='auditpattern',
            name='recommended_action',
            field=models.CharField(choices=[('NO_ACTION', 'No Action Required'), ('NOTIFY_ADMIN', 'Notify Administrator'), ('NOTIFY_SECURITY', 'Notify Security Team'), ('LOCK_USER', 'Lock User Account'), ('FORCE_LOGOUT', 'Force Logout'), ('RESET_PASSWORD', 'Force Password Reset'), ('ENABLE_MFA', 'Enable Multi-Factor Authentication'), ('BLOCK_IP', 'Block IP Address'), ('ESCALATE', 'Escalate to Management'), ('GENERATE_REPORT', 'Generate Detailed Report'), ('CUSTOM', 'Custom Action')], default='NO_ACTION', max_length=30, verbose_name='Recommended Action'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='chart_config',
            field=models.JSONField(blank=True, default=dict, help_text='JSON configuration for layout visualization', verbose_name='Chart Configuration'),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='chart_config',
            field=models.JSONField(blank=True, default=dict, help_text='JSON configuration for visualization', verbose_name='Chart Configuration'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='chart_config',
            field=models.JSONField(blank=True, default=dict, help_text='JSON configuration for health visualization', verbose_name='Chart Configuration'),
        ),
        migrations.AddField(
            model_name='institutionalanalytics',
            name='chart_config',
            field=models.JSONField(blank=True, default=dict, help_text='JSON configuration for visualization', verbose_name='Chart Configuration'),
        ),
        migrations.AddField(
            model_name='kpimodel',
            name='chart_config',
            field=models.JSONField(blank=True, default=dict, help_text='JSON configuration for visualization', verbose_name='Chart Configuration'),
        ),
        migrations.AddField(
            model_name='predictivemodel',
            name='chart_config',
            field=models.JSONField(blank=True, default=dict, help_text='JSON configuration for visualization', verbose_name='Chart Configuration'),
        ),
        migrations.AddField(
            model_name='report',
            name='chart_config',
            field=models.JSONField(blank=True, default=dict, help_text='JSON configuration for visualization', verbose_name='Chart Configuration'),
        ),
        migrations.AddField(
            model_name='reportexecution',
            name='chart_config',
            field=models.JSONField(blank=True, default=dict, help_text='JSON configuration for result visualization', verbose_name='Chart Configuration'),
        ),
        migrations.AddField(
            model_name='studentperformanceanalytics',
            name='chart_config',
            field=models.JSONField(blank=True, default=dict, help_text='JSON configuration for visualization', verbose_name='Chart Configuration'),
        ),
        migrations.AlterField(
            model_name='auditalert',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='auditanalysisreport',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_audit_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditdashboard',
            name='layout_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='auditdashboard',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_dashboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditdashboard',
            name='widget_configs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='auditmetric',
            name='group_by_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='auditmetric',
            name='query_filter',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='auditpattern',
            name='detection_rules',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Widget Configuration'),
        ),
        migrations.AlterField(
            model_name='predictivemodel',
            name='feature_columns',
            field=models.JSONField(blank=True, default=list, verbose_name='Feature Columns'),
        ),
        migrations.AlterField(
            model_name='report',
            name='config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Report Configuration'),
        ),
        migrations.AlterField(
            model_name='reportexecution',
            name='executed_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_executions', to=settings.AUTH_USER_MODEL, verbose_name='Executed By'),
        ),
        migrations.AlterField(
            model_name='studentperformanceanalytics',
            name='subject_performance',
            field=models.JSONField(blank=True, default=dict, verbose_name='Subject-wise Performance'),
        ),
    ]
